# Generated by Django 5.0.6 on 2024-07-26 21:55

from django.db import migrations
from django.conf import settings

def migrate_profile_data(apps, schema_editor):
    """
    Copia los datos de foto_perfil y firma desde el antiguo modelo Profile
    al nuevo modelo Usuario.
    """
    try:
        # Obtenemos el modelo Profile del estado histórico de las migraciones.
        # Esto es crucial porque el modelo Profile ya no existe en el código actual (users/models.py).
        Profile = apps.get_model('users', 'Profile')
        Usuario = apps.get_model('users', 'Usuario')

        for profile in Profile.objects.all():
            try:
                # Buscamos el usuario correspondiente
                usuario = Usuario.objects.get(id=profile.user_id)
                
                # Copiamos los campos. Nos aseguramos de manejar los casos
                # en los que los campos de imagen pudieran no tener un archivo asociado.
                if profile.foto_perfil:
                    usuario.foto_perfil = profile.foto_perfil
                if profile.firma:
                    usuario.firma = profile.firma
                
                # Guardamos solo si hemos hecho algún cambio.
                if profile.foto_perfil or profile.firma:
                    usuario.save()
            
            except Usuario.DoesNotExist:
                # Si por alguna razón un perfil apunta a un usuario que no existe,
                # simplemente lo ignoramos y continuamos con el siguiente.
                continue
                
    except LookupError:
        # Si el modelo Profile no se encuentra en el estado histórico (por ejemplo, si
        # la base de datos se crea desde cero con las nuevas migraciones),
        # simplemente no hacemos nada.
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_profile_data, reverse_code=migrations.RunPython.noop),
    ]
