# Generated by Django 5.2.4 on 2025-07-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_created_by_profile_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='firma',
            field=models.ImageField(blank=True, help_text='Firma digitalizada del usuario.', null=True, upload_to='firmas_usuarios/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
    ]
