# Generated by Django 5.2.4 on 2025-07-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='imagen_url',
        ),
        migrations.AddField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen principal del evento.', null=True, upload_to='eventos_imagenes/'),
        ),
        migrations.AddField(
            model_name='evento',
            name='is_pinned',
            field=models.BooleanField(db_index=True, default=False, help_text='Marca esta opción para fijar el evento al inicio.'),
        ),
    ]
