# Generated by Django 5.2.4 on 2025-07-16 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_remove_evento_imagen_url_evento_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(db_index=True, max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoría de Evento',
                'verbose_name_plural': 'Categorías de Eventos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Categoría a la que pertenece el evento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='eventos.categoria'),
        ),
    ]
