# Generated by Django 5.2.4 on 2025-07-16 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_categoria_evento_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(db_index=True, max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('insignia', models.ImageField(blank=True, help_text='Icono o insignia que representa el valor.', null=True, upload_to='valores_insignias/')),
            ],
            options={
                'verbose_name': 'Valor de la Empresa',
                'verbose_name_plural': 'Valores de la Empresa',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='valor',
            field=models.ForeignKey(blank=True, help_text='Si este evento es un reconocimiento, asigna el valor correspondiente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconocimientos', to='eventos.valor'),
        ),
    ]
