# Generated by Django 5.2.4 on 2025-07-23 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_categoria_created_by_categoria_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['-fecha'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterField(
            model_name='evento',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='eventos.categoria'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='eventos_imagenes/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='is_pinned',
            field=models.BooleanField(db_index=True, default=False, help_text='Fija el evento al inicio del feed.'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='valor',
            field=models.ForeignKey(blank=True, help_text="Asociar solo si el evento es un 'Reconocimiento'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconocimientos', to='eventos.valor'),
        ),
    ]
