# Generated by Django 5.2.4 on 2025-07-24 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_alter_evento_options_alter_evento_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='valor',
        ),
        migrations.DeleteModel(
            name='Valor',
        ),
    ]
