# Generated by Django 5.2.4 on 2025-07-25 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_alter_evento_options_alter_categoria_nombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Marcar para mantener el evento al principio de la lista.', verbose_name='Fijado'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
    ]
