# Generated by Django 5.2.4 on 2025-07-23 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_devicetoken_created_by_devicetoken_updated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicetoken',
            options={'ordering': ['-created_at'], 'verbose_name': 'Token de Dispositivo', 'verbose_name_plural': 'Tokens de Dispositivos'},
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si el token es válido para recibir notificaciones.'),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='token',
            field=models.CharField(help_text='Token de registro de Firebase Cloud Messaging.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='destinatario',
            field=models.ForeignKey(blank=True, help_text='Usuario específico a notificar. Nulo para notificaciones broadcast.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='error_message',
            field=models.TextField(blank=True, help_text='Mensaje de error si el envío falla.', null=True),
        ),
    ]
