# Generated by Django 5.2.4 on 2025-07-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0003_alter_devicetoken_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='estado',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='datos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='leido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='mensaje',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='titulo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
