# Generated by Django 5.2.4 on 2025-07-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatbotcategory_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotknowledgebase',
            name='is_recommended',
            field=models.BooleanField(db_index=True, default=False, help_text='Marcar para mostrar como una pregunta sugerida en el chat.'),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='session_id',
            field=models.CharField(db_index=True, help_text='ID para agrupar interacciones de una misma conversación.', max_length=100),
        ),
    ]
