# Generated by Django 5.2.4 on 2025-07-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chatbotknowledgebase_is_recommended_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbotknowledgebase',
            name='is_recommended',
        ),
        migrations.AddField(
            model_name='chatbotknowledgebase',
            name='recommended_questions',
            field=models.ManyToManyField(blank=True, help_text='Selecciona otras preguntas de la base de conocimiento para sugerir después de esta respuesta.', to='chatbot.chatbotknowledgebase', verbose_name='Preguntas Recomendadas'),
        ),
    ]
