# Generated by Django 5.2.4 on 2025-07-25 02:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_chatbotknowledgebase_view_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatbotcategory',
            options={'verbose_name': 'Categoría de Chatbot', 'verbose_name_plural': 'Categorías de Chatbot'},
        ),
        migrations.AlterModelOptions(
            name='chatbotknowledgebase',
            options={'ordering': ['-view_count'], 'verbose_name': 'Base de Conocimiento del Chatbot', 'verbose_name_plural': 'Bases de Conocimiento del Chatbot'},
        ),
        migrations.AlterModelOptions(
            name='chatconversation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Conversación de Chat', 'verbose_name_plural': 'Conversaciones de Chat'},
        ),
        migrations.AlterField(
            model_name='chatbotcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='chatbotknowledgebase',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.chatbotcategory', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='chatbotknowledgebase',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chatbotknowledgebase',
            name='keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='chatbotknowledgebase',
            name='recommended_questions',
            field=models.ManyToManyField(blank=True, to='chatbot.chatbotknowledgebase', verbose_name='Preguntas Recomendadas'),
        ),
        migrations.AlterField(
            model_name='chatbotknowledgebase',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Vistas'),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='answer_text',
            field=models.TextField(verbose_name='Texto de la Respuesta'),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='matched_knowledge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.chatbotknowledgebase', verbose_name='Conocimiento Coincidente'),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='question_text',
            field=models.TextField(verbose_name='Texto de la Pregunta'),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='session_id',
            field=models.CharField(default=uuid.uuid4, max_length=255, verbose_name='ID de Sesión'),
        ),
    ]
