# Generated by Django 5.2.4 on 2025-07-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_alter_chatconversation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotknowledgebase',
            name='question_embedding',
            field=models.JSONField(blank=True, help_text='El vector semántico de la pregunta, pre-calculado para búsquedas rápidas.', null=True, verbose_name='Vector de la Pregunta (Embedding)'),
        ),
    ]
