# Generated by Django 5.2.4 on 2025-07-28 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_chatbotknowledgebase_question_embedding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatbotknowledgebase',
            options={'ordering': ['-created_at'], 'verbose_name': 'Base de Conocimiento del Chatbot', 'verbose_name_plural': 'Bases de Conocimiento del Chatbot'},
        ),
    ]
