# Generated by Django 5.2.4 on 2025-07-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_alter_chatbotknowledgebase_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
