# Generated by Django 5.2.4 on 2025-08-02 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Almuerzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('fecha', models.DateField(help_text='Fecha exacta del almuerzo', unique=True, verbose_name='Fecha')),
                ('entrada', models.CharField(help_text='Plato de entrada del menú', max_length=100, verbose_name='Entrada')),
                ('plato_fondo', models.CharField(help_text='Plato principal del menú', max_length=100, verbose_name='Plato de fondo')),
                ('refresco', models.CharField(help_text='Bebida incluida en el menú', max_length=50, verbose_name='Refresco')),
                ('es_feriado', models.BooleanField(default=False, help_text='Indica si no se atiende ese día por ser feriado', verbose_name='Es feriado')),
                ('link', models.URLField(blank=True, help_text='Link para hacer el pedido del almuerzo', null=True, verbose_name='Link de pedido')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Almuerzo',
                'verbose_name_plural': 'Almuerzos',
                'ordering': ['fecha'],
            },
        ),
    ]
