# Generated by Django 5.2.4 on 2025-08-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almuerzos', '0002_add_active_and_dieta_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almuerzo',
            name='active',
            field=models.BooleanField(default=True, help_text='Almuerzo disponible para pedidos', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='almuerzo',
            name='dieta',
            field=models.CharField(blank=True, help_text='Menú especial de dieta', max_length=100, null=True, verbose_name='Dieta'),
        ),
        migrations.AlterField(
            model_name='almuerzo',
            name='entrada',
            field=models.CharField(help_text='Plato de entrada', max_length=100, verbose_name='Entrada'),
        ),
        migrations.AlterField(
            model_name='almuerzo',
            name='es_feriado',
            field=models.BooleanField(default=False, help_text='Día sin servicio por feriado', verbose_name='Es feriado'),
        ),
        migrations.AlterField(
            model_name='almuerzo',
            name='fecha',
            field=models.DateField(help_text='Fecha del almuerzo', unique=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='almuerzo',
            name='link',
            field=models.URLField(blank=True, help_text='URL para realizar pedidos', null=True, verbose_name='Link de pedido'),
        ),
        migrations.AlterField(
            model_name='almuerzo',
            name='plato_fondo',
            field=models.CharField(help_text='Plato principal', max_length=100, verbose_name='Plato de fondo'),
        ),
        migrations.AlterField(
            model_name='almuerzo',
            name='refresco',
            field=models.CharField(help_text='Bebida del menú', max_length=50, verbose_name='Refresco'),
        ),
    ]
